# Generated by Django 2.2.17 on 2020-12-18 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=200)),
                ('datedeb', models.DateField()),
                ('datefin', models.DateField()),
                ('statut', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('datenaissance', models.DateField()),
                ('email', models.CharField(max_length=200)),
                ('mdp', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('suppr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nbheure', models.IntegerField()),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Chantier')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.Employe')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='chantiers',
            field=models.ManyToManyField(through='timesheet.Timesheet', to='timesheet.Chantier'),
        ),
    ]
